modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "visualoverhaul"
version = "${version}"
displayName = "VisualOverhaul"
authors = "Motschen, TeamMidnightDust"
description = '''
Adds better visuals for certain Minecraft Vanilla Blocks.
'''
logoFile = "icon.png"
[[mixins]]
config = "visualoverhaul.mixins.json"
[[mixins]]
config = "visualoverhaul-neoforge.mixins.json"

[[dependencies.visualoverhaul]]
modId = "neoforge"
required = true
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.visualoverhaul]]
modId = "minecraft"
required = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.visualoverhaul]]
modId = "midnightlib"
required = true
versionRange = "[1.0.0,)"
ordering = "BEFORE"
side = "CLIENT"

[[dependencies.visualoverhaul]]
modId = "architectury"
required = true
versionRange = "[6.0.0,)"
ordering = "BEFORE"
side = "BOTH"